Port = 51000
APIPort = 56000
KeyHex = "THIS_IS_A_PRIVATE_KEY_THAT_IS_FORMATTED_WITH_HEX"
ObseverPort = 55000
FormulatorPort = 57000
StoreRoot = "./observer"
ForceRecover = true

[ObserverKeyMap]
3e5PNobd577YEdjeb59zG6N7BBZbyRKMja2s55QQMQE = "citygame_observer1.fleta.io:55000"
4ry8UmsCbo1BPTmUhqjMWgy9UtLDFcebEsc4Lgjo9ba = "citygame_observer2.fleta.io:55000"
4KT4crmdp5GDihPXufUonmAujjC1YH4viej8C1udjc4 = "citygame_observer3.fleta.io:55000"
3suqtMQWdUFUwDGMzH53KRJPFzqaP6YYRqRGMPLhhp5 = "citygame_observer4.fleta.io:55000"
3HLUjZYeUDc7nGKqCaRyqB8yJHwj3BgFMWUYNmMSYfE = "citygame_observer5.fleta.io:55000"
