SeedNodes = [
	"testnet_seednode1.fleta.io:51000",
	"testnet_seednode2.fleta.io:51000",
	"testnet_seednode3.fleta.io:51000",
	"testnet_seednode4.fleta.io:51000",
	"testnet_seednode5.fleta.io:51000"
]
ObserverKeys = [
	"3e5PNobd577YEdjeb59zG6N7BBZbyRKMja2s55QQMQE",
	"4ry8UmsCbo1BPTmUhqjMWgy9UtLDFcebEsc4Lgjo9ba",
	"4KT4crmdp5GDihPXufUonmAujjC1YH4viej8C1udjc4",
	"3suqtMQWdUFUwDGMzH53KRJPFzqaP6YYRqRGMPLhhp5",
	"3HLUjZYeUDc7nGKqCaRyqB8yJHwj3BgFMWUYNmMSYfE"
]
Port = 51000
APIPort = 56000
ServerPort = 52000
KeyHex = "THIS_IS_A_PRIVATE_KEY_THAT_IS_FORMATTED_WITH_HEX"
StoreRoot = "./data"
ForceRecover = true
