SeedNodes = [
	"citygame_seednode1.fleta.io:51000",
	"citygame_seednode2.fleta.io:51000",
	"citygame_seednode3.fleta.io:51000",
	"citygame_seednode4.fleta.io:51000",
	"citygame_seednode5.fleta.io:51000"
]
ObserverKeys = [
	"cz6z1egYG1rMAcj8SDJYMh5rCyBfEXG7TXMjZVQSrV",
	"3k4UM4ocDcExYuAxH9y1z7YL6C8EkWxdnr7mWZkHa4B",
	"4Ub3zq1McCNBvrvUtxAagC7QWtCqzqfzYUW5cYpo6Uz",
	"4SYZHismJGWgLEe9ty7zZVEVdYDnFLvg5YNh1pddakJ",
	"BoL8aayw42NWUdgJKEscJLvnGwHHr9c5L2kkvbRyhM"
]
Port = 51000
APIPort = 58000
ExplorerPort = 59001
StoreRoot = "./data"
ForceRecover = true
